// ══════════════════════════════════════════════════════════════
// Digital Product Studio: Export Utilities
// Pure functions to build listing.txt and metadata.json
// content for listing package ZIP exports.
// ══════════════════════════════════════════════════════════════

import type { DigitalProduct } from "@/types/digital-product";
import { DIGITAL_PRODUCT_LABELS } from "@/types/digital-product";

// ── Listing Text Builder ─────────────────────────────────────

/**
 * Builds a human-readable listing.txt for Etsy copy-paste.
 */
export function buildListingText(product: DigitalProduct): string {
  const { listing, config, productType, projectName } = product;
  const lines: string[] = [];

  lines.push("═══════════════════════════════════════════════════");
  lines.push(`  ${projectName}`);
  lines.push(`  ${DIGITAL_PRODUCT_LABELS[productType]} — Etsy Listing Package`);
  lines.push("═══════════════════════════════════════════════════");
  lines.push("");

  // Title
  lines.push("── TITLE ──────────────────────────────────────────");
  lines.push(listing.title || "(No title set)");
  lines.push(`   Characters: ${listing.title.length}/140`);
  lines.push("");

  // Description
  lines.push("── DESCRIPTION ────────────────────────────────────");
  lines.push(listing.description || "(No description set)");
  lines.push("");

  // Tags
  lines.push("── TAGS ───────────────────────────────────────────");
  if (listing.tags.length > 0) {
    lines.push(listing.tags.join(", "));
    lines.push(`   Count: ${listing.tags.length}/13`);
  } else {
    lines.push("(No tags set)");
  }
  lines.push("");

  // Price
  lines.push("── PRICING ────────────────────────────────────────");
  lines.push(`   Minimum:     $${listing.price.min.toFixed(2)}`);
  lines.push(`   Recommended: $${listing.price.recommended.toFixed(2)}`);
  lines.push(`   Maximum:     $${listing.price.max.toFixed(2)}`);
  lines.push("");

  // FAQs
  if (listing.faqs.length > 0) {
    lines.push("── FAQs ───────────────────────────────────────────");
    for (const faq of listing.faqs) {
      lines.push(`Q: ${faq.question}`);
      lines.push(`A: ${faq.answer}`);
      lines.push("");
    }
  }

  // Product Configuration Summary
  lines.push("── PRODUCT DETAILS ────────────────────────────────");
  lines.push(`   Type: ${DIGITAL_PRODUCT_LABELS[productType]}`);

  if (config) {
    switch (config.type) {
      case "pdf":
        lines.push(`   Planner Type: ${config.plannerType}`);
        lines.push(`   Color Theme:  ${config.colorTheme}`);
        lines.push(`   Paper Size:   ${config.paperSize}`);
        if (config.year) lines.push(`   Year:         ${config.year}`);
        if (config.customTitle) lines.push(`   Custom Title: ${config.customTitle}`);
        break;
      case "excel":
        lines.push(`   Tracker Type:  ${config.trackerType}`);
        lines.push(`   Color Scheme:  ${config.colorScheme}`);
        if (config.customCategories?.length) {
          lines.push(`   Categories:    ${config.customCategories.join(", ")}`);
        }
        break;
      case "printable":
        lines.push(`   Printable Type: ${config.printableType}`);
        lines.push(`   Color Scheme:   ${config.colorScheme}`);
        if (config.quoteTheme) lines.push(`   Quote Theme:    ${config.quoteTheme}`);
        break;
      case "notion":
        lines.push(`   Template Type: ${config.templateType}`);
        lines.push(`   Aesthetic:     ${config.aesthetic}`);
        lines.push(`   Complexity:    ${config.complexity}`);
        lines.push(`   Premium:       ${config.premium ? "Yes" : "No"}`);
        break;
    }
  }
  lines.push("");

  // Quality Score
  if (product.qualityScore) {
    lines.push("── QUALITY SCORE ──────────────────────────────────");
    lines.push(`   Overall: ${product.qualityScore.overall}/100 (${product.qualityScore.tier})`);
    lines.push(`   Content:       ${product.qualityScore.breakdown.content}/25`);
    lines.push(`   Design:        ${product.qualityScore.breakdown.design}/25`);
    lines.push(`   Completeness:  ${product.qualityScore.breakdown.completeness}/25`);
    lines.push(`   Etsy Readiness:${product.qualityScore.breakdown.etsyReadiness}/25`);
    lines.push(`   Est. Price:    $${product.qualityScore.etsyPriceEstimate.min} – $${product.qualityScore.etsyPriceEstimate.max}`);
    lines.push("");
  }

  // Batch Info
  if (product.batchMeta) {
    lines.push("── BATCH INFO ─────────────────────────────────────");
    lines.push(`   Variant:  ${product.batchMeta.variantLabel}`);
    lines.push(`   Position: ${product.batchMeta.variantIndex + 1} of ${product.batchMeta.totalVariants}`);
    lines.push(`   Batch ID: ${product.batchMeta.batchId}`);
    lines.push("");
  }

  lines.push("───────────────────────────────────────────────────");
  lines.push(`Generated by CraftPlan Digital Studio`);
  lines.push(`Date: ${new Date().toISOString().split("T")[0]}`);

  return lines.join("\n");
}

// ── Metadata JSON Builder ────────────────────────────────────

/**
 * Builds a structured metadata.json for programmatic use.
 */
export function buildMetadataJson(product: DigitalProduct): object {
  return {
    version: "1.0",
    generatedAt: new Date().toISOString(),
    project: {
      id: product.id,
      name: product.projectName,
      productType: product.productType,
      status: product.status,
    },
    config: product.config,
    listing: {
      title: product.listing.title,
      description: product.listing.description,
      tags: product.listing.tags,
      price: product.listing.price,
      faqs: product.listing.faqs,
    },
    qualityScore: product.qualityScore
      ? {
          overall: product.qualityScore.overall,
          tier: product.qualityScore.tier,
          breakdown: product.qualityScore.breakdown,
          etsyPriceEstimate: product.qualityScore.etsyPriceEstimate,
        }
      : null,
    batchMeta: product.batchMeta,
    generation: product.generation.result
      ? {
          type: product.generation.result.type,
          completedAt: product.generation.completedAt,
          ...(product.generation.result.type === "file"
            ? {
                fileName: product.generation.result.fileName,
                fileSizeBytes: product.generation.result.fileSizeBytes,
                mimeType: product.generation.result.mimeType,
              }
            : {
                pageUrl: product.generation.result.pageUrl,
                databases: product.generation.result.databases,
                qualityTier: product.generation.result.qualityTier,
              }),
        }
      : null,
  };
}
