// ══════════════════════════════════════════════════════════════
// Product Factory Types
// 5-engine automatic Etsy product creation pipeline:
//   Research → Blueprint → Generate → Images → Copy
// ══════════════════════════════════════════════════════════════

import type { DigitalProductType, DigitalProductConfig, DigitalQualityScore, SheetsConfig } from "./digital-product";

// ── Factory Run ─────────────────────────────────────────────

export type FactoryRunStatus =
  | "pending"
  | "scanning"
  | "blueprinting"
  | "generating"
  | "imaging"
  | "listing"
  | "packaging"
  | "completed"
  | "ready_to_list"
  | "failed"
  | "cancelled";

export type FactoryEngine = 1 | 2 | 3 | 4 | 5;

export interface FactoryEngineLog {
  engine: FactoryEngine;
  name: string;
  status: "pending" | "running" | "done" | "error" | "skipped";
  durationMs?: number;
  error?: string;
  output?: Record<string, unknown>;
}

export interface FactoryRun {
  id: string;
  status: FactoryRunStatus;

  // Input
  keywords?: string[];
  opportunityId?: number;
  selectedListingId?: string;

  // Engine outputs
  blueprintId?: string;
  projectId?: string;
  listingImages?: string[];       // Asset IDs
  deliveryPdfAssetId?: string;

  // Tracking
  engineLog: FactoryEngineLog[];
  errorMessage?: string;
  startedAt?: string;
  completedAt?: string;
  createdAt: string;
}

// ── Blueprint ───────────────────────────────────────────────

export interface BlueprintDifferentiation {
  competitorStrengths: string[];
  competitorWeaknesses: string[];
  ourImprovements: string[];
  positioningAngle: string;
  suggestedPrice: { min: number; max: number; recommended: number };
}

export interface BlueprintListingStrategy {
  titleKeywords: string[];
  positionAs: "premium" | "value" | "comprehensive";
  uniqueSellingPoints: string[];
}

export type FactoryProductType = DigitalProductType | "sheets" | "google-sheets";
export type FactoryProductConfig = DigitalProductConfig | SheetsConfig;

export interface FactoryBlueprint {
  id: string;
  factoryRunId: string;
  opportunityId?: number;
  sourceListingTitle?: string;

  // Competitor analysis
  competitorStrengths: string[];
  competitorWeaknesses: string[];

  // Product spec
  productType: FactoryProductType;
  config: FactoryProductConfig;
  differentiation: BlueprintDifferentiation;
  listingStrategy: BlueprintListingStrategy;

  // Meta
  suggestedPrice: number;
  positioning: string;
  createdAt: string;
}

// ── Product Blueprint (detailed spec for GWS generation) ────

export interface BlueprintTab {
  name: string;
  purpose: string;
  columns: Array<{
    name: string;
    type: "text" | "currency" | "percent" | "date" | "formula" | "number";
    width?: number;
    formula?: string;
  }>;
  sampleRows: Array<Array<string | number | null>>;
  features: Array<"frozen_header" | "dropdown_validation" | "conditional_formatting" | "sparkline" | "chart" | "alternating_rows">;
  /**
   * Optional: route this tab to a rich, hand-crafted layout builder
   * instead of the standard column-driven data builders. When set, the
   * `columns`/`sampleRows` arrays are ignored and the layout builder
   * paints the worksheet directly from the Python reference recipe.
   */
  richLayout?: "smart-calendar" | "year-in-review" | "money-coach" | "what-if-simulator";
}

export interface BlueprintChart {
  type: "pie" | "donut" | "bar" | "column" | "line";
  title: string;
  sourceTab: string;
  sourceRange: string;        // e.g. "B2:B6" for labels
  dataRange: string;          // e.g. "D2:D6" for values
  placement: { tab: string; row: number; col: number };
  width?: number;
  height?: number;
}

export interface ProductBlueprint extends FactoryBlueprint {
  // Detailed product spec
  tabs: BlueprintTab[];
  charts: BlueprintChart[];
  colorScheme: {
    primary: string;     // hex e.g. "#1B3A5C"
    secondary: string;
    accent: string;
    background: string;
    text: string;
    success: string;
    danger: string;
  };
  sampleDataStrategy: string;
  deliveryMethod: "xlsx_download" | "sheets_link" | "both";

  // ── Gemini-First Spec Chain ──
  // These specs are generated by Gemini and drive all creative decisions.
  // Claude consumes them for deterministic building/rendering/packaging.

  /** AI-generated visual direction — controls all image/video composition */
  visualDirection?: import("./visual-direction").VisualDirectionSpec;
  /** AI-generated product concept — WHO, WHAT, WHY */
  conceptSpec?: import("./gemini-specs").ProductConceptSpec;
  /** AI-generated product structure — sections, tabs, pages */
  structureSpec?: import("./gemini-specs").ProductStructureSpec;
  /** AI-generated video creative brief */
  videoDirection?: import("./gemini-specs").VideoDirectionSpec;
  /** AI-generated listing positioning strategy */
  listingPositioning?: import("./gemini-specs").ListingPositioningSpec;
  /** AI-generated copy tone and voice direction */
  copyDirection?: import("./gemini-specs").CopyDirectionSpec;
}

// ── GWS Generation Plan ─────────────────────────────────────

export interface GwsGenerationPlan {
  spreadsheetTitle: string;
  spreadsheetId?: string;
  phases: Array<{
    name: string;
    commands: string[];
  }>;
  totalCommands: number;
}

// ── Research Scan Results ────────────────────────────────────

export interface OpportunityScore {
  demand: number;        // 0-100: favorites, sales, velocity
  competition: number;   // 0-100: how crowded (inverted — high = low competition)
  growth: number;        // 0-100: velocity, trend signals
  clarity: number;       // 0-100: clear problem/solution match
  differentiation: number; // 0-100: room to improve
  overall: number;       // 0-100: weighted composite
}

export interface OpportunityListing {
  id: number;
  listingId: string;
  title: string;
  url?: string;
  shopName?: string;
  price: number;
  favorites: number;
  salesEstimate: number;
  reviewCount: number;
  ageDays: number;
  isBestseller: boolean;
  tags: string[];
  sourceKeyword?: string;
  revenueEstimate: number;
  score: OpportunityScore;
  whyItWins: string[];
  improvementAngles: string[];
}

export interface NichePattern {
  commonTabs: string[];
  commonFeatures: string[];
  commonPriceRange: { min: number; max: number; avg: number };
  commonVisualPatterns: string[];
  commonTagPatterns: string[];
  bundleSignals: string[];
  avgReviews: number;
  avgSalesEstimate: number;
}

export interface OpportunityRecommendation {
  keyword: string;
  suggestedProductCategory: string;
  reason: string;
  blueprintAngle: string;
  priority: "high" | "medium" | "low";
  topCompetitor: { title: string; price: number; reviews: number };
}

export interface ScanResult {
  scanId: string;
  keyword: string;
  productType: "sheets" | "pdf" | "excel" | "printable" | "notion";
  totalMatches: number;
  topListings: OpportunityListing[];
  patterns: NichePattern;
  recommendations: OpportunityRecommendation[];
  scannedAt: string;
}

// Legacy compat
export type ScanOpportunity = OpportunityListing;

// ── Listing Image Plan ──────────────────────────────────────

export type ListingImageKind =
  | "thumbnail"
  | "problem"
  | "dashboard"
  | "feature"
  | "method"
  | "included"
  | "delivery"
  // Family-specific narrative slots
  | "kpi-hero"           // Executive: full KPI strip hero (no device frame, data-forward)
  | "vendor-zoom"        // Editorial/Wedding: close-up on vendor or guest data
  | "itinerary-preview"  // Editorial/Travel: itinerary table showcase
  | "milestone-tracker"  // Nurture: savings goals or milestones progress
  | "bills-calendar"     // Paycheck: bills due dates and sinking funds
  | "debt-progress"      // Paycheck/Debt: debt payoff progress visualization
  | "pl-breakdown"       // Executive: P&L or revenue vs expense comparison
  | "social-proof"       // Any: trust/review/rating slide
  | "comparison"         // Any: before/after or us-vs-competitor slide
  // Dynamic sequence kinds (from VisualDirectionSpec.imageSequence)
  | "detail-zoom"        // Close-up of specific tab/feature
  | "lifestyle"          // Aspirational context shot
  | "guarantee"          // Money-back, satisfaction, trust
  // Meal planner slots
  | "meal-plan-zoom"     // Meal planner: weekly meal plan grid close-up
  | "grocery-zoom"       // Meal planner: grocery list with costs close-up
  // Student budget slots
  | "semester-zoom"      // Student: semester costs breakdown close-up
  | "subscription-audit" // Student: subscription audit table close-up
  // Debt payoff slots
  | "debt-overview"      // Debt: debt accounts with APR/payoff close-up
  | "snowball-zoom"      // Debt: month-by-month snowball tracker close-up
  | "milestones";        // Debt: payoff milestone celebrations close-up

export type CropIntent = "full" | "kpi" | "chart" | "table" | "section" | "tabs-bar";
export type MockupType = "laptop" | "tablet" | "fullscreen" | "split-layout" | "text-slide";
export type OverlayStyle = "bold-dark" | "clean-light" | "minimal-premium";

export interface ListingImageSpec {
  id: string;                 // "img_1" through "img_7"
  slot: number;               // 1-7 (Etsy listing position)
  kind: ListingImageKind;
  title: string;              // Main overlay text
  subtitle?: string;          // Secondary text
  sourceTab?: string;         // Which spreadsheet tab to capture
  sourceRange?: string;       // e.g. "A1:L23" — what cell range to show
  cropIntent?: CropIntent;    // How to frame the capture
  highlights?: string[];      // Specific elements to call out (arrows, circles)
  mockupType: MockupType;     // How the image is framed
  overlayStyle: OverlayStyle; // Text overlay aesthetic
  notes?: string;             // Implementation notes for manual capture or future automation
}

export interface ListingImagePlan {
  factoryRunId: string;
  blueprintId: string;
  productType: "sheets" | "pdf" | "excel" | "printable" | "notion";
  productName: string;
  thumbnailIndex: number;     // Which slot is the recommended thumbnail (usually 1)
  colorScheme: {              // For overlay consistency
    primary: string;
    accent: string;
    background: string;
  };
  images: ListingImageSpec[];
  captureInstructions: string; // Human-readable summary of what to capture
}

// Legacy compat — keep for existing code that references these
export type ListingImage = ListingImageSpec & { assetId: string; downloadUrl: string; width: number; height: number };
export interface ListingImageSet { factoryRunId: string; images: ListingImage[]; }

// ── Listing Copy Package ────────────────────────────────────

export interface ListingCopyPackage {
  factoryRunId: string;
  blueprintId: string;
  productType: "sheets" | "pdf" | "excel" | "printable" | "notion";
  niche: string;

  // Titles
  titleOptions: string[];
  recommendedTitle: string;

  // Tags (Etsy max 13, each max 20 chars)
  tags: string[];

  // Hero text
  thumbnailText: string;
  shortHook: string;

  // Full description (Etsy listing body)
  fullDescription: string;

  // FAQ
  faq: Array<{ question: string; answer: string }>;

  // Pricing
  pricing: {
    launchPrice: number;
    standardPrice: number;
    bundlePriceSuggestion?: number;
    rationale: string;
  };

  // Differentiation
  differentiators: string[];

  // Image captions (tied to ListingImagePlan)
  imageCaptions: Array<{ imageSlot: number; caption: string }>;

  // Delivery
  deliveryInstructions: string;
}

// ── Factory Package ─────────────────────────────────────────

export type PackageFileKind =
  | "product"
  | "instructions_txt"
  | "listing_txt"
  | "listing_json"
  | "image_plan_json"
  | "meta_json";

export interface PackageFile {
  fileName: string;
  kind: PackageFileKind;
  sizeBytes?: number;
}

export interface FactoryPackageResult {
  factoryRunId: string;
  productType: "sheets" | "pdf" | "excel" | "printable" | "notion";
  zipAssetId?: string;
  zipDownloadUrl?: string;
  includedFiles: PackageFile[];
  summary: {
    title: string;
    productFileName: string;
    hasInstructions: boolean;
    hasListingCopy: boolean;
    hasImagePlan: boolean;
    totalFiles: number;
  };
}

// ── Factory Run API ─────────────────────────────────────────

export type FactoryRunMode =
  | "full"                 // scan → pick best → full pipeline
  | "single_best"         // alias for full with autoPickTop=true
  | "selected_opportunity" // user picked a specific opportunity
  | "from-opportunity"    // legacy alias for selected_opportunity
  | "from-blueprint"      // skip scan+blueprint, start from existing
  | "top_n";              // build top N from a niche (batch)

export interface FactoryRunInput {
  mode: FactoryRunMode;
  keywords?: string[];
  opportunityId?: number;
  listingId?: string;
  blueprintId?: string;
  productTypeOverride?: FactoryProductType;
  autoPickTop?: boolean;
  /** For top_n mode: how many products to build */
  topN?: number;
  /** Pre-loaded opportunity data (avoids re-scanning) */
  opportunityData?: {
    title: string;
    tags?: string[];
    price?: number;
    reviews?: number;
    revenueEstimate?: number;
    niche?: string;
    description?: string;
    listingId?: string;
    imageUrls?: string[];
    ideaContext?: {
      title?: string;
      whyNow?: string;
      targetBuyer?: string;
    };
    marketContext?: {
      competition?: number | null;
      avgFavorites?: number | null;
      evidenceCount?: number;
      topTags?: string[];
    };
  };
}

export interface FactoryRunOutput {
  factoryRunId: string;
  status: FactoryRunStatus;
  currentEngine?: FactoryEngine;
  engineStatuses: FactoryEngineLog[];
  projectId?: string;
  blueprintId?: string;
  qualityScore?: DigitalQualityScore;
  listingPackageReady: boolean;
  /** Populated when status is ready_to_list */
  readyToList?: ReadyToListPackage;
}

/** Everything needed to publish a product on Etsy */
export interface ReadyToListPackage {
  productAsset?: { assetId: string; downloadUrl: string; fileName: string };
  listingImages?: Array<{ slot: number; kind: string; assetId: string; downloadUrl: string }>;
  listingCopy?: {
    title: string;
    tags: string[];
    description: string;
    price: number;
    /** Anchor/original price for sale display (shown in description) */
    originalPrice?: number;
  };
  packageAsset?: { assetId: string; downloadUrl: string };
  /** URL to real-time Playwright preview of the spreadsheet dashboard */
  previewUrl?: string;
  /** URL to the generated listing video */
  videoUrl?: string;
  /** Blueprint ID for fetching previews */
  blueprintId?: string;
  /** Google Sheet ID (when built via Google Sheets API) */
  googleSheetId?: string;
  /** Direct URL to open the Google Sheet in the browser */
  googleSheetUrl?: string;
  suggestedPrice?: number;
  totalDurationMs?: number;
  /** Internal: Google Sheet ID for delivery PDF generation */
  _googleSheetId?: string;
  /** Internal: Product title for delivery PDF */
  _title?: string;
  /** Internal: Project ID for asset storage */
  _projectId?: string;
  /** Which builder produced the spreadsheet (gemini-exceljs | premium-template | legacy) */
  builderPath?: string;
  /** Gemini-generated product name (when builderPath === "gemini-exceljs") */
  geminiProductName?: string;
  /** Number of tabs in the generated spreadsheet */
  tabCount?: number;
  /** Multi-aesthetic variants — separate .xlsx files for different palettes (Etsy SKU multiplier) */
  variants?: Array<{
    key: string;
    label: string;
    fileName: string;
    fileSizeBytes: number;
    downloadUrl?: string;
    assetId?: string;
  }>;
}

// ── Etsy Publish Handoff ─────────────────────────────────────

export type EtsyPublishState = "draft_ready" | "publishing" | "draft_created" | "active" | "failed";

export interface EtsyPublishPayload {
  sourceRunId: string;
  blueprintId?: string;
  projectId?: string;

  // Listing metadata
  title: string;
  description: string;
  tags: string[];
  price: number;

  // Image assets (ordered by slot for Etsy listing photos)
  imageAssets: Array<{
    assetId: string;
    downloadUrl: string;
    slot: number;
    kind: string;
  }>;

  // The product file customers download
  digitalFileAsset?: {
    assetId: string;
    downloadUrl: string;
    fileName: string;
  };

  // ZIP bundle with instructions + listing copy
  packageAsset?: {
    assetId: string;
    downloadUrl: string;
  };

  // Etsy-specific
  taxonomyId: number;
  productType: "digital";
  categoryHint?: string;

  // Google Sheets delivery (when product is a Google Sheet)
  _googleSheetId?: string;

  // State
  state: EtsyPublishState;

  // After publish
  etsyListingId?: number;
  etsyListingUrl?: string;
}

export interface EtsyPublishResult {
  success: boolean;
  sourceRunId: string;
  etsyListingId?: number;
  etsyListingUrl?: string;
  etsyStatus: "draft" | "active";
  stepsCompleted: string[];
  errors: string[];
}

// ── Publish Review Gate ─────────────────────────────────────

export type ReviewStatus =
  | "pending_review"
  | "approved"
  | "blocked_duplicate"
  | "blocked_quality";

export interface ReviewCheck {
  id: string;
  label: string;
  status: "pass" | "warn" | "fail";
  message: string;
  details?: string;
}

export interface SimilarListing {
  runId: string;
  title: string;
  niche: string;
  titleSimilarity: number;
  etsyListingId?: number;
  etsyListingUrl?: string;
  etsyStatus?: string;
}

export interface ReviewScorecard {
  runId: string;
  reviewedAt: string;

  // Product info
  title: string;
  niche: string;
  price: number;
  originalPrice: number;
  imageCount: number;
  imageUrls: string[];
  tagCount: number;
  tags: string[];
  hasProductFile: boolean;
  hasThumbnail: boolean;
  descriptionLength: number;

  // Checks
  checks: ReviewCheck[];

  // Duplicates
  similarListings: SimilarListing[];
  maxTitleSimilarity: number;

  // Niche
  nicheActiveCount: number;
  nicheLimit: number;
  nicheExceeded: boolean;

  // Verdict
  recommendation: "approve" | "review" | "block";
  blockReasons: string[];
  warnings: string[];
  canApprove: boolean;

  // Current review status from DB
  reviewStatus: ReviewStatus | null;
}

// ── Factory Store ───────────────────────────────────────────

export interface FactoryStoreState {
  // Active runs
  runs: FactoryRun[];
  activeRunId: string | null;

  // Scan results
  lastScan: ScanResult | null;

  // UI state
  isScanning: boolean;
  isRunning: boolean;

  // Actions
  startRun: (input: FactoryRunInput) => Promise<string>;
  updateRun: (runId: string, updates: Partial<FactoryRun>) => void;
  setActiveRun: (runId: string | null) => void;
  setScanResult: (result: ScanResult | null) => void;
  refreshRuns: () => Promise<void>;
}
