// ══════════════════════════════════════════════════════════════
// Gemini-First Spec System
//
// These specs are generated by Gemini and form the creative
// brief for the entire product pipeline. Claude/deterministic
// code consumes these specs to build actual products.
//
// Spec chain:
//   ProductConceptSpec → ProductStructureSpec
//     → VisualDirectionSpec (existing)
//     → VideoDirectionSpec
//     → ListingPositioningSpec
//     → CopyDirectionSpec
//
// Each spec has:
//   - version field for schema evolution
//   - bounded enums / clamped numbers for safe consumption
//   - clampXxx() validator following VisualDirectionSpec pattern
// ══════════════════════════════════════════════════════════════

// ── Product Types ──────────────────────────────────────────────

export type GeminiProductType =
  | "google-sheets"
  | "excel-tracker"
  | "notion-template"
  | "pdf-planner"
  | "printable-kit"
  | "delivery-pdf";

// ── ProductConceptSpec ─────────────────────────────────────────
// WHO is this for, WHAT makes it unique, WHY should they buy it

export interface ProductConceptSpec {
  version: 1;

  /** Broad product type */
  productType: GeminiProductType;
  /** Machine-readable niche slug */
  niche: string;
  /** Human-readable niche label */
  nicheLabel: string;
  /** Target customer persona (1-2 sentences) */
  targetCustomer: string;
  /** Top 3-5 pain points the customer has */
  customerPainPoints: string[];
  /** One-sentence value proposition */
  productPromise: string;
  /** How this differs from competitors */
  uniqueAngle: string;
  /** Emotional hook for marketing */
  emotionalHook: string;
  /** Price tier */
  pricePositioning: "budget" | "mid" | "premium" | "luxury";
  /** Recommended retail price in USD */
  recommendedPrice: number;
  /** Competitive intelligence */
  competitorInsights: {
    strengths: string[];
    weaknesses: string[];
    ourImprovements: string[];
  };
  /** Brand personality keywords (3-5 adjectives) */
  brandPersonality: string[];
  /** Suggested product name/title */
  suggestedTitle: string;
}

// ── ProductStructureSpec ───────────────────────────────────────
// WHAT does this product contain — structure varies by product type

export interface ProductStructureSpec {
  version: 1;

  /** Must match the concept's product type */
  productType: GeminiProductType;
  /** Product display title */
  title: string;
  /** Subtitle / tagline */
  subtitle: string;

  /** Universal section list — every product type has sections */
  sections: ProductSection[];

  /** Type-specific extensions (only one populated per spec) */
  sheets?: SheetsStructure;
  notion?: NotionStructure;
  pdf?: PdfStructure;
  printable?: PrintableStructure;
  excel?: ExcelStructure;
}

export interface ProductSection {
  id: string;
  name: string;
  purpose: string;
  order: number;
  contentType:
    | "dashboard" | "data-entry" | "summary" | "tracker"
    | "reference" | "instructions" | "calendar" | "checklist"
    | "gallery" | "overview" | "settings";
  subsections?: ProductSubsection[];
}

export interface ProductSubsection {
  id: string;
  name: string;
  type:
    | "kpi-row" | "data-table" | "chart" | "text-block"
    | "checklist" | "progress-tracker" | "timeline"
    | "grid" | "form" | "image-block" | "divider";
}

// ── Sheets-specific structure ──────────────────────────────────

export interface SheetsStructure {
  tabs: SheetsTabSpec[];
  charts: SheetsChartSpec[];
  colorScheme: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    text: string;
    success: string;
    danger: string;
  };
  sampleDataStrategy: string;
  deliveryMethod: "xlsx_download" | "sheets_link" | "both";
  /** Niche-specific KPI model — what metrics matter */
  kpiModel: SheetsKpiModel;
  /** Dashboard personality */
  dashboardStyle: "data-heavy" | "visual-focused" | "balanced" | "minimal-clean";
}

export interface SheetsTabSpec {
  name: string;
  purpose: string;
  tabType: "dashboard" | "data-entry" | "reference" | "settings" | "summary" | "tracker";
  columns: SheetsColumnSpec[];
  sampleRowCount: number;
  features: Array<
    | "frozen_header" | "dropdown_validation" | "conditional_formatting"
    | "sparkline" | "chart" | "alternating_rows" | "data_validation"
    | "pivot_summary" | "named_ranges"
  >;
  /** Section hierarchy within the tab */
  sections?: Array<{
    name: string;
    startRow: number;
    type: "header" | "kpi-strip" | "data-table" | "chart-area" | "summary-row" | "notes";
  }>;
}

export interface SheetsColumnSpec {
  name: string;
  type: "text" | "currency" | "percent" | "date" | "formula" | "number" | "dropdown" | "checkbox";
  width?: number;
  formula?: string;
  dropdownOptions?: string[];
  conditionalFormat?: {
    rule: "positive-green" | "negative-red" | "threshold" | "gradient";
    threshold?: number;
  };
}

export interface SheetsChartSpec {
  type: "pie" | "donut" | "bar" | "column" | "line" | "area" | "sparkline" | "gauge";
  title: string;
  sourceTab: string;
  purpose: string;
  placement: { tab: string; row: number; col: number };
  width?: number;
  height?: number;
}

export interface SheetsKpiModel {
  /** Primary metric (e.g., "Net Savings", "Total Revenue", "Trip Budget Left") */
  primaryMetric: string;
  /** Secondary metrics (e.g., "Monthly Spending", "Debt Payoff Progress") */
  secondaryMetrics: string[];
  /** Comparison basis */
  comparisonType: "month-over-month" | "budget-vs-actual" | "goal-progress" | "category-breakdown";
  /** Niche-specific goal type */
  goalType?: string;
}

// ── Notion-specific structure ──────────────────────────────────

export interface NotionStructure {
  pages: NotionPageSpec[];
  databases: NotionDatabaseSpec[];
  /** Root page layout */
  rootLayout: "sidebar-nav" | "gallery-grid" | "list-view" | "board-kanban";
  /** Visual theme */
  coverStyle: "gradient" | "photo" | "illustration" | "minimal";
}

export interface NotionPageSpec {
  title: string;
  icon: string;
  blocks: Array<{
    type: "heading" | "paragraph" | "callout" | "toggle" | "divider"
      | "database-view" | "embed" | "image" | "quote" | "checklist";
    content?: string;
    databaseRef?: string;
  }>;
}

export interface NotionDatabaseSpec {
  id: string;
  name: string;
  properties: Array<{
    name: string;
    type: "title" | "text" | "number" | "select" | "multi-select"
      | "date" | "checkbox" | "url" | "formula" | "relation" | "rollup";
    options?: string[];
    formula?: string;
  }>;
  views: Array<{
    type: "table" | "board" | "calendar" | "gallery" | "list" | "timeline";
    name: string;
    filter?: string;
    sort?: string;
  }>;
}

// ── PDF-specific structure ─────────────────────────────────────

export interface PdfStructure {
  pageSize: "letter" | "a4" | "a5" | "half-letter";
  orientation: "portrait" | "landscape";
  pages: PdfPageSpec[];
  /** Style family controls overall aesthetic */
  styleFamily: "modern-clean" | "hand-drawn" | "minimal" | "bold-color" | "elegant-serif";
  /** Color palette for the PDF */
  palette: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    text: string;
  };
}

export interface PdfPageSpec {
  pageNumber: number;
  type: "cover" | "toc" | "content" | "tracker" | "worksheet" | "calendar"
    | "checklist" | "notes" | "reference" | "divider";
  title?: string;
  sections: Array<{
    type: "header" | "grid" | "lined-area" | "checklist" | "table"
      | "chart-placeholder" | "image-area" | "text-block" | "prompt-box";
    rows?: number;
    cols?: number;
    prompt?: string;
  }>;
}

// ── Printable-specific structure ───────────────────────────────

export interface PrintableStructure {
  format: "single-sheet" | "multi-page" | "card-set" | "sticker-sheet" | "poster";
  printSize: "letter" | "a4" | "5x7" | "4x6" | "8x10";
  pages: PrintablePageSpec[];
  styleFamily: "whimsical" | "minimal" | "bold" | "vintage" | "modern";
  cutLines: boolean;
}

export interface PrintablePageSpec {
  type: "activity" | "tracker" | "planner" | "card" | "label" | "poster" | "worksheet";
  title: string;
  layout: "single" | "grid-2x2" | "grid-3x3" | "list" | "freeform";
  elements: Array<{
    type: "text" | "checkbox" | "image-placeholder" | "line" | "box" | "icon";
    content?: string;
  }>;
}

// ── Excel-specific structure ───────────────────────────────────

export interface ExcelStructure {
  /** Inherits from SheetsStructure with Excel-specific extensions */
  tabs: SheetsTabSpec[];
  charts: SheetsChartSpec[];
  colorScheme: SheetsStructure["colorScheme"];
  /** Excel-specific features */
  useMacros: boolean;
  usePivotTables: boolean;
  useNamedRanges: boolean;
  /** VBA module descriptions (if useMacros) */
  macroDescriptions?: string[];
}

// ── VideoDirectionSpec ─────────────────────────────────────────
// Standalone video creative brief — richer than the VisualDirectionSpec.video section

export interface VideoDirectionSpec {
  version: 1;

  /** Opening hook text */
  hookText: string;
  /** Hook animation style */
  hookStyle: "text-fade" | "zoom-reveal" | "slide-in" | "dramatic-dark" | "split-reveal";
  /** Ordered scene list */
  scenes: VideoScene[];
  /** Default pace per scene (ms) */
  defaultPaceMs: number;
  /** End card CTA text */
  ctaText: string;
  /** Music/mood hint */
  musicMood: "upbeat" | "calm" | "professional" | "emotional" | "energetic";
  /** Scene transition style */
  transitionStyle: "fade" | "slide" | "zoom" | "cut" | "morph";
  /** Total target duration in seconds */
  targetDurationSec: number;
  /** Emotional arc (what viewer should feel at each stage) */
  emotionalArc: string[];
}

export interface VideoScene {
  type: "intro" | "hook" | "reveal" | "zoom" | "scroll" | "tab-switch"
    | "callout" | "comparison" | "testimonial" | "end-card";
  durationMs: number;
  /** Which section/tab to highlight */
  focusArea?: string;
  /** On-screen caption */
  caption?: string;
  /** Zoom target (CSS selector or section name) */
  zoomTarget?: string;
  /** Camera motion */
  motion?: "static" | "pan-left" | "pan-right" | "zoom-in" | "zoom-out" | "scroll-down";
}

// ── ListingPositioningSpec ─────────────────────────────────────
// Marketing strategy for the Etsy listing

export interface ListingPositioningSpec {
  version: 1;

  /** Target audience persona (detailed) */
  audiencePersona: string;
  /** Primary benefit — the #1 reason to buy */
  primaryBenefit: string;
  /** Supporting benefits (3-5) */
  secondaryBenefits: string[];
  /** Marketing hook angle */
  hookAngle: string;
  /** Emotional triggers to leverage */
  emotionalTriggers: string[];
  /** Common objections and how to handle them */
  objectionHandlers: Array<{
    objection: string;
    response: string;
  }>;
  /** Social proof angle */
  socialProofAngle: string;
  /** Urgency element (optional) */
  urgencyElement?: string;
  /** Bundle/upsell opportunity */
  bundleOpportunity?: string;
  /** SEO keywords to emphasize */
  seoKeywords: string[];
  /** Category positioning */
  categoryPosition: "market-leader" | "premium-alternative" | "budget-friendly" | "niche-specialist";
}

// ── CopyDirectionSpec ──────────────────────────────────────────
// Tone and voice for all generated copy

export interface CopyDirectionSpec {
  version: 1;

  /** Overall tone */
  tone: "warm" | "professional" | "energetic" | "luxurious" | "practical" | "playful";
  /** Power words to use in copy */
  vocabulary: string[];
  /** Words/phrases to avoid */
  avoidWords: string[];
  /** Emoji usage level */
  emojiStyle: "heavy" | "moderate" | "minimal" | "none";
  /** Sentence structure preference */
  sentenceStyle: "short-punchy" | "flowing" | "mixed";
  /** CTA directness */
  ctaStyle: "soft" | "direct" | "urgent";
  /** Brand voice description (1 sentence) */
  brandVoice: string;
  /** Title format preference */
  titleFormat: "emoji-heavy" | "keyword-first" | "benefit-first" | "question-hook";
  /** Description structure */
  descriptionStructure: "story-first" | "benefits-first" | "features-first" | "problem-solution";
}

// ══════════════════════════════════════════════════════════════
// VALIDATORS — clampXxx() functions for each spec
// Same pattern as VisualDirectionSpec.clampSpec()
// ══════════════════════════════════════════════════════════════

const clamp = (val: number | undefined, min: number, max: number, def: number) =>
  typeof val === "number" ? Math.max(min, Math.min(max, val)) : def;

const enumVal = <T extends string>(val: unknown, allowed: T[], def: T): T =>
  allowed.includes(val as T) ? (val as T) : def;

const strVal = (val: unknown, def: string): string =>
  typeof val === "string" && val.length > 0 ? val : def;

const arrVal = <T>(val: unknown, def: T[]): T[] =>
  Array.isArray(val) && val.length > 0 ? val : def;

// ── clampConceptSpec ───────────────────────────────────────────

export function clampConceptSpec(raw: Partial<ProductConceptSpec>): ProductConceptSpec {
  return {
    version: 1,
    productType: enumVal(raw.productType, ["google-sheets", "excel-tracker", "notion-template", "pdf-planner", "printable-kit", "delivery-pdf"], "google-sheets"),
    niche: strVal(raw.niche, "budget_tracker"),
    nicheLabel: strVal(raw.nicheLabel, "Budget Tracker"),
    targetCustomer: strVal(raw.targetCustomer, "People who want to manage their money better"),
    customerPainPoints: arrVal(raw.customerPainPoints, ["No clear view of spending", "Always over budget"]),
    productPromise: strVal(raw.productPromise, "Take control of your finances in 5 minutes a day"),
    uniqueAngle: strVal(raw.uniqueAngle, "Beautiful, easy-to-use design that makes budgeting enjoyable"),
    emotionalHook: strVal(raw.emotionalHook, "Stop stressing about money"),
    pricePositioning: enumVal(raw.pricePositioning, ["budget", "mid", "premium", "luxury"], "mid"),
    recommendedPrice: clamp(raw.recommendedPrice, 1.99, 49.99, 7.99),
    competitorInsights: {
      strengths: arrVal(raw.competitorInsights?.strengths, ["Established shops"]),
      weaknesses: arrVal(raw.competitorInsights?.weaknesses, ["Generic templates"]),
      ourImprovements: arrVal(raw.competitorInsights?.ourImprovements, ["Better visual design"]),
    },
    brandPersonality: arrVal(raw.brandPersonality, ["approachable", "professional", "trustworthy"]),
    suggestedTitle: strVal(raw.suggestedTitle, "Budget Tracker Google Sheets Template"),
  };
}

// ── clampStructureSpec ─────────────────────────────────────────

export function clampStructureSpec(raw: Partial<ProductStructureSpec>): ProductStructureSpec {
  return {
    version: 1,
    productType: enumVal(raw.productType, ["google-sheets", "excel-tracker", "notion-template", "pdf-planner", "printable-kit", "delivery-pdf"], "google-sheets"),
    title: strVal(raw.title, "Budget Tracker"),
    subtitle: strVal(raw.subtitle, "Google Sheets Template"),
    sections: arrVal(raw.sections, [
      { id: "s1", name: "Dashboard", purpose: "Overview of finances", order: 1, contentType: "dashboard" as const },
      { id: "s2", name: "Transactions", purpose: "Log income and expenses", order: 2, contentType: "data-entry" as const },
    ]),
    sheets: raw.sheets,
    notion: raw.notion,
    pdf: raw.pdf,
    printable: raw.printable,
    excel: raw.excel,
  };
}

// ── clampVideoDirectionSpec ────────────────────────────────────

export function clampVideoDirectionSpec(raw: Partial<VideoDirectionSpec>): VideoDirectionSpec {
  return {
    version: 1,
    hookText: strVal(raw.hookText, "Stop guessing where your money goes."),
    hookStyle: enumVal(raw.hookStyle, ["text-fade", "zoom-reveal", "slide-in", "dramatic-dark", "split-reveal"], "text-fade"),
    scenes: arrVal(raw.scenes, [
      { type: "intro" as const, durationMs: 2000 },
      { type: "reveal" as const, durationMs: 3000, focusArea: "Dashboard" },
      { type: "scroll" as const, durationMs: 2000, focusArea: "Transactions" },
      { type: "end-card" as const, durationMs: 2000 },
    ]),
    defaultPaceMs: clamp(raw.defaultPaceMs, 1000, 5000, 2500),
    ctaText: strVal(raw.ctaText, "Get yours today — instant download."),
    musicMood: enumVal(raw.musicMood, ["upbeat", "calm", "professional", "emotional", "energetic"], "professional"),
    transitionStyle: enumVal(raw.transitionStyle, ["fade", "slide", "zoom", "cut", "morph"], "fade"),
    targetDurationSec: clamp(raw.targetDurationSec, 15, 60, 30),
    emotionalArc: arrVal(raw.emotionalArc, ["curiosity", "recognition", "excitement", "action"]),
  };
}

// ── clampListingPositioningSpec ────────────────────────────────

export function clampListingPositioningSpec(raw: Partial<ListingPositioningSpec>): ListingPositioningSpec {
  return {
    version: 1,
    audiencePersona: strVal(raw.audiencePersona, "Budget-conscious individuals looking for a simple tracking system"),
    primaryBenefit: strVal(raw.primaryBenefit, "See exactly where your money goes"),
    secondaryBenefits: arrVal(raw.secondaryBenefits, ["Easy to customize", "Beautiful design", "Instant download"]),
    hookAngle: strVal(raw.hookAngle, "The spreadsheet that makes budgeting actually enjoyable"),
    emotionalTriggers: arrVal(raw.emotionalTriggers, ["control", "relief", "confidence"]),
    objectionHandlers: arrVal(raw.objectionHandlers, [
      { objection: "I can make my own spreadsheet", response: "This saves you 20+ hours of design and formula work" },
    ]),
    socialProofAngle: strVal(raw.socialProofAngle, "Trusted by thousands of smart budgeters"),
    urgencyElement: raw.urgencyElement,
    bundleOpportunity: raw.bundleOpportunity,
    seoKeywords: arrVal(raw.seoKeywords, ["budget tracker", "google sheets template"]),
    categoryPosition: enumVal(raw.categoryPosition, ["market-leader", "premium-alternative", "budget-friendly", "niche-specialist"], "premium-alternative"),
  };
}

// ── clampCopyDirectionSpec ─────────────────────────────────────

export function clampCopyDirectionSpec(raw: Partial<CopyDirectionSpec>): CopyDirectionSpec {
  return {
    version: 1,
    tone: enumVal(raw.tone, ["warm", "professional", "energetic", "luxurious", "practical", "playful"], "warm"),
    vocabulary: arrVal(raw.vocabulary, ["effortless", "beautiful", "smart", "instant"]),
    avoidWords: arrVal(raw.avoidWords, ["cheap", "basic", "simple"]),
    emojiStyle: enumVal(raw.emojiStyle, ["heavy", "moderate", "minimal", "none"], "moderate"),
    sentenceStyle: enumVal(raw.sentenceStyle, ["short-punchy", "flowing", "mixed"], "mixed"),
    ctaStyle: enumVal(raw.ctaStyle, ["soft", "direct", "urgent"], "direct"),
    brandVoice: strVal(raw.brandVoice, "Friendly expert who makes complex things feel easy"),
    titleFormat: enumVal(raw.titleFormat, ["emoji-heavy", "keyword-first", "benefit-first", "question-hook"], "keyword-first"),
    descriptionStructure: enumVal(raw.descriptionStructure, ["story-first", "benefits-first", "features-first", "problem-solution"], "problem-solution"),
  };
}
