// ══════════════════════════════════════════════════════════════
// VisualDirectionSpec — AI-Driven Creative Layout System
//
// Generated by Gemini per product. Controls every visual
// decision in the image renderer. No hardcoded templates.
//
// Each field maps to a concrete rendering parameter.
// Enums are bounded. Numbers are clamped at consumption.
// This makes the spec safe to render even with edge-case AI output.
// ══════════════════════════════════════════════════════════════

export interface VisualDirectionSpec {
  version: 1;

  // ── Global Composition ──
  global: {
    /** Background rendering mode */
    backgroundMode: "gradient" | "solid" | "split" | "radial";
    /** Gradient direction in degrees (0=top-to-bottom, 90=left-to-right) */
    gradientAngle: number;
    /** Two color stops [start, end] as hex */
    gradientStops: [string, string];
    /** Decorative scatter elements */
    decorStyle: "circles" | "dots" | "lines" | "diamonds" | "none";
    /** Decorative element opacity (0.02–0.12) */
    decorOpacity: number;
    /** Primary font style across all slides */
    fontFamily: "sans" | "serif" | "mono";
    /** Overall visual density */
    density: "spacious" | "balanced" | "dense";
  };

  // ── Hero/Thumbnail (Slot 1) ──
  hero: {
    /** Device composition */
    deviceLayout: "single-laptop" | "multi-device" | "flatlay" | "phone-pair" | "tablet-solo";
    /** Primary device rotation in degrees (-15 to 15) */
    deviceRotation: number;
    /** Title placement */
    titlePosition: "top-center" | "top-left" | "bottom-center" | "overlay";
    /** Title font size multiplier (0.7–1.4) */
    titleScale: number;
    /** Feature pill placement */
    pillsPosition: "bottom-row" | "left-column" | "hidden";
    /** Gemini background prompt hint */
    backgroundHint: string;
  };

  // ── Problem/Hook (Slot 2) ──
  problem: {
    /** Slide layout structure */
    layout: "centered-text" | "split-columns" | "stacked-cards" | "diagonal" | "full-dark";
    /** Hook text size multiplier (0.8–1.5) */
    hookScale: number;
    /** Background darkness (0=white, 1=fully dark) */
    darkness: number;
    /** Show pain point bullets */
    showBullets: boolean;
    /** Number of pain points (2–5) */
    bulletCount: number;
    /** Visual separator between hook and solution */
    separator: "line" | "ornament" | "gradient" | "none";
    /** Content vertical position */
    gravity: "top" | "center" | "bottom";
  };

  // ── Dashboard/KPI (Slot 3) ──
  dashboard: {
    /** KPI card count */
    kpiCount: number;
    /** KPI arrangement */
    kpiLayout: "horizontal-strip" | "grid-2x2" | "vertical-stack" | "large-hero-plus-small";
    /** Show data table section */
    showTable: boolean;
    /** Data table rows (3–8) */
    tableRows: number;
    /** Show visualization */
    showViz: boolean;
    /** Visualization type */
    vizType: "bars" | "progress-rings" | "sparklines" | "donut";
    /** Section display order */
    sections: Array<"kpis" | "table" | "viz" | "goals">;
    /** Gemini-defined dashboard blocks — rendered in order, each is a visual unit */
    blocks: DashboardBlock[];
    /** Overall layout density */
    layoutDensity: "spacious" | "balanced" | "dense" | "minimal";
  };

  // ── Feature/Niche (Slot 4) ──
  feature: {
    /** Primary visual type */
    vizType: "progress-bars" | "comparison-table" | "stat-cards" | "checklist" | "timeline";
    /** Number of items (3–6) */
    itemCount: number;
    /** Show a hero stat callout at top */
    showHeroStat: boolean;
    /** Card arrangement */
    arrangement: "vertical" | "horizontal" | "grid" | "staggered";
  };

  // ── Method/How-It-Works (Slot 5) ──
  method: {
    /** Number of steps */
    stepCount: number;
    /** Step visual layout */
    layout: "horizontal-cards" | "vertical-timeline" | "numbered-list" | "zigzag" | "icon-grid";
    /** Connector between steps */
    connector: "arrow" | "dotted" | "numbered" | "none";
    /** Card shape */
    cardShape: "rounded" | "circle" | "pill" | "square";
    /** Show icons per step */
    showIcons: boolean;
  };

  // ── Included/What's Inside (Slot 6) ──
  included: {
    /** Grid columns */
    columns: number;
    /** Card visual style */
    cardStyle: "bordered" | "filled" | "minimal" | "icon-left";
    /** Show a count badge (e.g. "7 Tabs Included") */
    showCountBadge: boolean;
  };

  // ── Delivery (Slot 7) ──
  delivery: {
    /** Number of steps */
    stepCount: number;
    /** Layout style */
    layout: "horizontal-flow" | "vertical-steps" | "icon-row";
    /** Trust badges */
    badges: string[];
    /** Show device compatibility row */
    showDeviceRow: boolean;
  };

  // ── Image Sequence — Gemini defines which images, in what order ──
  imageSequence: ImageSequenceSlot[];

  // ── Video Direction ──
  video: {
    /** Opening hook style */
    introStyle: "text-fade" | "zoom-reveal" | "slide-in" | "dramatic-dark";
    /** Scene pacing in ms */
    scenePaceMs: number;
    /** Which tabs to highlight in order */
    tabHighlights: string[];
    /** End card CTA text */
    ctaText: string;
  };
}

// ── Dashboard Block ──
// Each block is a visual unit that the spreadsheet renderer places in order.
// Gemini decides which blocks exist, their order, and their style.
// The renderer iterates blocks and builds the spreadsheet row by row.

export type DashboardBlockType =
  | "kpi-cards"         // KPI summary cards (income, expenses, profit, etc.)
  | "category-table"    // Budget categories with columns
  | "bar-chart"         // REPT-based horizontal bar chart (budget vs actual)
  | "progress-tracker"  // Visual progress bars (savings goals, debt payoff)
  | "insights"          // Auto-generated insight formulas
  | "checklist"         // Checkbox-style task list (wedding tasks, packing, etc.)
  | "summary-stats"     // Small summary row with key numbers
  | "top-categories"    // Top N spending categories as a mini highlight
  | "goals-grid"        // Savings/investment goals in a grid
  | "monthly-comparison" // Month-over-month comparison row
  | "niche-section";     // Config-driven niche sections from dashConfig.sections

export interface DashboardBlock {
  type: DashboardBlockType;
  /** Block title (shown as section header) */
  title: string;
  /** Emoji prefix for the section header */
  emoji: string;
  /** Visual style hint */
  style: "large" | "compact" | "minimal" | "visual-bars" | "horizontal" | "cards" | "checklist-style";
  /** How many data rows to show (for tables/lists) */
  rowCount?: number;
  /** Data source key */
  dataSource?: "budgetCategories" | "savingsGoals" | "custom";
  /** Width: full, left-half, right-half */
  width: "full" | "left" | "right";
}

// ── Image Sequence Slot ──
// Each slot describes ONE image in the listing.
// Gemini decides count (5–10), types, order, titles.
// The renderer follows this sequence instead of a fixed template.

export type ImageSlotKind =
  | "thumbnail"     // Hero product shot
  | "problem"       // Emotional pain-point hook
  | "dashboard"     // KPI / data overview
  | "feature"       // Charts, progress, tracking
  | "method"        // How it works / system
  | "included"      // What's inside / tab grid
  | "delivery"      // Download & setup flow
  | "social-proof"  // Reviews, testimonials, trust
  | "comparison"    // Before/after or vs-competitor
  | "detail-zoom"   // Close-up of specific tab/feature
  | "lifestyle"     // Aspirational context shot
  | "guarantee";    // Money-back, satisfaction, trust

export interface ImageSequenceSlot {
  /** Image position (1-based) */
  slot: number;
  /** What kind of image */
  kind: ImageSlotKind;
  /** Primary text overlay */
  title: string;
  /** Secondary text overlay */
  subtitle: string;
  /** Which tab to screenshot (role-based: "dashboard", "transactions", etc.) */
  sourceTabRole: string;
  /** Crop intent: "full" | "kpi" | "table" | "section" | "chart" */
  cropIntent: string;
  /** Why this image is here — storytelling purpose */
  narrativePurpose: string;
}

// ── Clamp/Validate Helper ──

export function clampSpec(raw: Partial<VisualDirectionSpec>): VisualDirectionSpec {
  const g = raw.global || {} as VisualDirectionSpec["global"];
  const h = raw.hero || {} as VisualDirectionSpec["hero"];
  const p = raw.problem || {} as VisualDirectionSpec["problem"];
  const d = raw.dashboard || {} as VisualDirectionSpec["dashboard"];
  const f = raw.feature || {} as VisualDirectionSpec["feature"];
  const m = raw.method || {} as VisualDirectionSpec["method"];
  const inc = raw.included || {} as VisualDirectionSpec["included"];
  const del = raw.delivery || {} as VisualDirectionSpec["delivery"];
  const v = raw.video || {} as VisualDirectionSpec["video"];

  const clamp = (val: number | undefined, min: number, max: number, def: number) =>
    typeof val === "number" ? Math.max(min, Math.min(max, val)) : def;

  const enumVal = <T extends string>(val: unknown, allowed: T[], def: T): T =>
    allowed.includes(val as T) ? (val as T) : def;

  return {
    version: 1,
    global: {
      backgroundMode: enumVal(g.backgroundMode, ["gradient", "solid", "split", "radial"], "gradient"),
      gradientAngle: clamp(g.gradientAngle, 0, 360, 180),
      gradientStops: Array.isArray(g.gradientStops) && g.gradientStops.length === 2
        ? g.gradientStops : ["#F8F9FA", "#FFFFFF"],
      decorStyle: enumVal(g.decorStyle, ["circles", "dots", "lines", "diamonds", "none"], "none"),
      decorOpacity: clamp(g.decorOpacity, 0.02, 0.12, 0.05),
      fontFamily: enumVal(g.fontFamily, ["sans", "serif", "mono"], "sans"),
      density: enumVal(g.density, ["spacious", "balanced", "dense"], "balanced"),
    },
    hero: {
      deviceLayout: enumVal(h.deviceLayout, ["single-laptop", "multi-device", "flatlay", "phone-pair", "tablet-solo"], "multi-device"),
      deviceRotation: clamp(h.deviceRotation, -15, 15, 0),
      titlePosition: enumVal(h.titlePosition, ["top-center", "top-left", "bottom-center", "overlay"], "top-center"),
      titleScale: clamp(h.titleScale, 0.7, 1.4, 1.0),
      pillsPosition: enumVal(h.pillsPosition, ["bottom-row", "left-column", "hidden"], "bottom-row"),
      backgroundHint: typeof h.backgroundHint === "string" ? h.backgroundHint : "clean minimal desk",
    },
    problem: {
      layout: enumVal(p.layout, ["centered-text", "split-columns", "stacked-cards", "diagonal", "full-dark"], "centered-text"),
      hookScale: clamp(p.hookScale, 0.8, 1.5, 1.0),
      darkness: clamp(p.darkness, 0, 1, 0),
      showBullets: typeof p.showBullets === "boolean" ? p.showBullets : true,
      bulletCount: clamp(p.bulletCount, 2, 5, 3),
      separator: enumVal(p.separator, ["line", "ornament", "gradient", "none"], "line"),
      gravity: enumVal(p.gravity, ["top", "center", "bottom"], "center"),
    },
    dashboard: {
      kpiCount: clamp(d.kpiCount, 2, 5, 4),
      kpiLayout: enumVal(d.kpiLayout, ["horizontal-strip", "grid-2x2", "vertical-stack", "large-hero-plus-small"], "horizontal-strip"),
      showTable: typeof d.showTable === "boolean" ? d.showTable : true,
      tableRows: clamp(d.tableRows, 3, 8, 5),
      showViz: typeof d.showViz === "boolean" ? d.showViz : false,
      vizType: enumVal(d.vizType, ["bars", "progress-rings", "sparklines", "donut"], "bars"),
      sections: Array.isArray(d.sections) ? d.sections : ["kpis", "table"],
      blocks: clampDashboardBlocks(d.blocks),
      layoutDensity: enumVal(d.layoutDensity as string, ["spacious", "balanced", "dense", "minimal"], "balanced"),
    },
    feature: {
      vizType: enumVal(f.vizType, ["progress-bars", "comparison-table", "stat-cards", "checklist", "timeline"], "stat-cards"),
      itemCount: clamp(f.itemCount, 3, 6, 4),
      showHeroStat: typeof f.showHeroStat === "boolean" ? f.showHeroStat : false,
      arrangement: enumVal(f.arrangement, ["vertical", "horizontal", "grid", "staggered"], "vertical"),
    },
    method: {
      stepCount: clamp(m.stepCount, 3, 5, 3),
      layout: enumVal(m.layout, ["horizontal-cards", "vertical-timeline", "numbered-list", "zigzag", "icon-grid"], "horizontal-cards"),
      connector: enumVal(m.connector, ["arrow", "dotted", "numbered", "none"], "arrow"),
      cardShape: enumVal(m.cardShape, ["rounded", "circle", "pill", "square"], "rounded"),
      showIcons: typeof m.showIcons === "boolean" ? m.showIcons : true,
    },
    included: {
      columns: clamp(inc.columns, 2, 4, 3),
      cardStyle: enumVal(inc.cardStyle, ["bordered", "filled", "minimal", "icon-left"], "bordered"),
      showCountBadge: typeof inc.showCountBadge === "boolean" ? inc.showCountBadge : true,
    },
    delivery: {
      stepCount: clamp(del.stepCount, 2, 4, 3),
      layout: enumVal(del.layout, ["horizontal-flow", "vertical-steps", "icon-row"], "horizontal-flow"),
      badges: Array.isArray(del.badges) ? del.badges.slice(0, 5) : ["Instant Download", "Lifetime Access"],
      showDeviceRow: typeof del.showDeviceRow === "boolean" ? del.showDeviceRow : true,
    },
    video: {
      introStyle: enumVal(v.introStyle, ["text-fade", "zoom-reveal", "slide-in", "dramatic-dark"], "text-fade"),
      scenePaceMs: clamp(v.scenePaceMs, 1000, 4000, 2000),
      tabHighlights: Array.isArray(v.tabHighlights) ? v.tabHighlights.slice(0, 5) : [],
      ctaText: typeof v.ctaText === "string" ? v.ctaText : "Get yours today.",
    },
    imageSequence: clampImageSequence(raw.imageSequence),
  };
}

const VALID_BLOCK_TYPES: DashboardBlockType[] = [
  "kpi-cards", "category-table", "bar-chart", "progress-tracker",
  "insights", "checklist", "summary-stats", "top-categories",
  "goals-grid", "monthly-comparison",
];

function clampDashboardBlocks(raw: unknown): DashboardBlock[] {
  if (!Array.isArray(raw) || raw.length === 0) return []; // empty = use legacy
  return raw
    .filter((b): b is Record<string, unknown> => typeof b === "object" && b !== null)
    .slice(0, 10)
    .map((b) => ({
      type: VALID_BLOCK_TYPES.includes(b.type as DashboardBlockType)
        ? (b.type as DashboardBlockType)
        : "category-table",
      title: typeof b.title === "string" ? b.title.slice(0, 60) : "",
      emoji: typeof b.emoji === "string" ? b.emoji.slice(0, 4) : "",
      style: (["large", "compact", "minimal", "visual-bars", "horizontal", "cards", "checklist-style"] as readonly string[])
        .includes(b.style as string)
        ? (b.style as DashboardBlock["style"])
        : "compact" as DashboardBlock["style"],
      rowCount: typeof b.rowCount === "number" ? Math.min(Math.max(b.rowCount, 1), 12) : undefined,
      dataSource: (["budgetCategories", "savingsGoals", "custom"] as readonly string[])
        .includes(b.dataSource as string)
        ? (b.dataSource as DashboardBlock["dataSource"])
        : undefined,
      width: (["full", "left", "right"] as readonly string[]).includes(b.width as string)
        ? (b.width as DashboardBlock["width"])
        : "full" as DashboardBlock["width"],
    }));
}

const VALID_SLOT_KINDS: ImageSlotKind[] = [
  "thumbnail", "problem", "dashboard", "feature", "method",
  "included", "delivery", "social-proof", "comparison",
  "detail-zoom", "lifestyle", "guarantee",
];

function clampImageSequence(
  raw: unknown,
): ImageSequenceSlot[] {
  if (!Array.isArray(raw) || raw.length === 0) return []; // empty = use legacy fallback
  return raw
    .filter((s): s is Record<string, unknown> => typeof s === "object" && s !== null)
    .slice(0, 10) // max 10 images
    .map((s, i) => ({
      slot: i + 1,
      kind: VALID_SLOT_KINDS.includes(s.kind as ImageSlotKind)
        ? (s.kind as ImageSlotKind)
        : "feature",
      title: typeof s.title === "string" ? s.title.slice(0, 80) : "",
      subtitle: typeof s.subtitle === "string" ? s.subtitle.slice(0, 120) : "",
      sourceTabRole: typeof s.sourceTabRole === "string" ? s.sourceTabRole : "",
      cropIntent: typeof s.cropIntent === "string" ? s.cropIntent : "full",
      narrativePurpose: typeof s.narrativePurpose === "string" ? s.narrativePurpose.slice(0, 200) : "",
    }));
}
